baseurl = ""
languageCode = "en-us"
title = "My Resume"
theme = "cv_theme"

# go to http://fontawesome.io/icons/ to change icons on skills and interests

[params]
  LinkedInID = "LinkedInID"
  GitlabID = "GitlabID"
  GithubID = "GithubID"
  TwitterID = "TwitterID"
  FacebookID = "FacebookID"

  Name = "Homer Simpson"
  Username = "user"
  Hostname = "host"
  BlogURL = "//myblog.me"
  Email = "me@email.me"
  About = "Software Engineer"
  Location = "City, Region, Country, Earth"
  #Avatar = "https://placehold.it/400x400"
  Avatar = "img/homer.png"
  GoogleAnalytics = "GoogleAnalyticsID"

  Skills = [
      ["Team Work", "100", "users"],
      ["Fedora", "95", "linux"],
      ["HTML5", "85", "html5"],
  ]
  Career = [
            ["Company1", "http://www.example.com", "Jul 2015 - Aug 2016", "SW engineer", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."],
            ["Company2", "http://www.example.com", "Jul 2015 - Aug 2016", "HW engineer", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."],
  ]
  Internships = [
            ["Company2", "http://www.example.com", "Jan 2015 - Jun 2015", "IT support", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."],
  ]
  Education = [
            ["University1", "http://www.example.es/", "2011 - 2015", "Bachelor of Computer Science"],
            ["University2", "http://www.example.es/", "2016-2017", "Master’s in Computer Science"],
  ]
  Interests = [
            ["Sports", "futbol-o", ""],
            ["Books", "book", "https://www.goodreads.com/user"],
            ["Tv Shows", "television", ""],
            ["People", "users", ""],
  ]
